### ISSUE TITLE
Development Documentation

### ISSUE THREAD

**Issue by S-DICKSON** [S-DICKSON/RecoveRiver-Eating-Disorder-App#1]
**About**
The read me of the application should contain instructions on how the developer setups up the development environment and the configuration of linters.

**Info**
It appears the app is set up in react native expo

- https://reactnative.dev/docs/environment-setup

**Todo**
- [ ] Setup react native expo
- [ ] Pull fork repo
- [ ] See if project runs
