### ISSUE TITLE
App Notifcations

### ISSUE THREAD

**Issue by S-DICKSON** [S-DICKSON/RecoveRiver-Eating-Disorder-App#4]
### Feature
The user should be able to select a time when the app sends a push notification.

**Todo**
- [ ] Implement the UI of the screen
- [ ] Research packages for push notifications
- [ ] Internal memory may be required to know what time app push notification

**Screen**
![image](https://user-images.githubusercontent.com/52682455/171700417-e617e1c9-c9b8-4b97-87a9-662749a04f9c.png)
